"""Initial schema setup

Revision ID: f1116377f84a
Revises: 001
Create Date: 2026-07-05 00:14:37.622560
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1116377f84a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True))
    op.alter_column('advertisements', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('advertisements', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_advertisements_id'), 'advertisements', ['id'], unique=False)
    op.create_foreign_key(None, 'advertisements', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_ai_explanations_id'), 'ai_explanations', ['id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user'), table_name='audit_logs')
    op.drop_constraint(op.f('authors_slug_key'), 'authors', type_='unique')
    op.drop_index(op.f('idx_authors_slug'), table_name='authors')
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_slug'), 'authors', ['slug'], unique=True)
    op.add_column('blog_calculators', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_blog_calculators_id'), 'blog_calculators', ['id'], unique=False)
    op.add_column('blog_media', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_blog_media_id'), 'blog_media', ['id'], unique=False)
    op.alter_column('blog_posts', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('blog_posts', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('blog_posts_slug_key'), 'blog_posts', type_='unique')
    op.drop_index(op.f('idx_blog_posts_author_id'), table_name='blog_posts')
    op.drop_index(op.f('idx_blog_posts_category_id'), table_name='blog_posts')
    op.drop_index(op.f('idx_blog_posts_slug'), table_name='blog_posts', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.drop_index(op.f('idx_blog_sections_blog_post_id'), table_name='blog_sections')
    op.create_index(op.f('ix_blog_sections_id'), 'blog_sections', ['id'], unique=False)
    op.add_column('bookmarks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_calculator_charts_id'), 'calculator_charts', ['id'], unique=False)
    op.create_index(op.f('ix_calculator_examples_id'), 'calculator_examples', ['id'], unique=False)
    op.drop_index(op.f('idx_calculator_faqs_calculator_id'), table_name='calculator_faqs')
    op.create_index(op.f('ix_calculator_faqs_id'), 'calculator_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_calculator_formulas_id'), 'calculator_formulas', ['id'], unique=False)
    op.drop_index(op.f('idx_calculator_inputs_calculator_id'), table_name='calculator_inputs')
    op.create_index(op.f('ix_calculator_inputs_id'), 'calculator_inputs', ['id'], unique=False)
    op.add_column('calculator_media', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_calculator_media_id'), 'calculator_media', ['id'], unique=False)
    op.drop_index(op.f('idx_calculator_outputs_calculator_id'), table_name='calculator_outputs')
    op.create_index(op.f('ix_calculator_outputs_id'), 'calculator_outputs', ['id'], unique=False)
    op.add_column('calculator_references', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_calculator_references_id'), 'calculator_references', ['id'], unique=False)
    op.create_index(op.f('ix_calculator_sections_id'), 'calculator_sections', ['id'], unique=False)
    op.alter_column('calculators', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('calculators', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('calculators_slug_key'), 'calculators', type_='unique')
    op.drop_index(op.f('idx_calculators_author_id'), table_name='calculators')
    op.drop_index(op.f('idx_calculators_category_id'), table_name='calculators')
    op.drop_index(op.f('idx_calculators_is_featured'), table_name='calculators', postgresql_where='((is_featured = true) AND (is_published = true))')
    op.drop_index(op.f('idx_calculators_slug'), table_name='calculators', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_calculators_id'), 'calculators', ['id'], unique=False)
    op.create_index(op.f('ix_calculators_slug'), 'calculators', ['slug'], unique=True)
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('idx_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('custom_pages_slug_key'), 'custom_pages', type_='unique')
    op.drop_index(op.f('idx_custom_pages_slug'), table_name='custom_pages')
    op.create_index(op.f('ix_custom_pages_id'), 'custom_pages', ['id'], unique=False)
    op.create_index(op.f('ix_custom_pages_slug'), 'custom_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_footer_columns_id'), 'footer_columns', ['id'], unique=False)
    op.create_index(op.f('ix_footer_links_id'), 'footer_links', ['id'], unique=False)
    op.add_column('guide_calculators', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_guide_calculators_id'), 'guide_calculators', ['id'], unique=False)
    op.add_column('guide_media', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_guide_media_id'), 'guide_media', ['id'], unique=False)
    op.drop_index(op.f('idx_guide_sections_guide_id'), table_name='guide_sections')
    op.create_index(op.f('ix_guide_sections_id'), 'guide_sections', ['id'], unique=False)
    op.alter_column('guides', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('guides', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('guides_slug_key'), 'guides', type_='unique')
    op.drop_index(op.f('idx_guides_slug'), table_name='guides', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_guides_id'), 'guides', ['id'], unique=False)
    op.create_index(op.f('ix_guides_slug'), 'guides', ['slug'], unique=True)
    op.create_index(op.f('ix_homepage_sections_id'), 'homepage_sections', ['id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_foreign_key(None, 'media', 'media_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_media_folders_id'), 'media_folders', ['id'], unique=False)
    op.drop_index(op.f('idx_navigation_items_parent'), table_name='navigation_items', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_navigation_items_id'), 'navigation_items', ['id'], unique=False)
    op.alter_column('newsletter_subscribers', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('newsletter_subscribers', 'subscribed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('newsletter_subscribers', 'unsubscribed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_newsletter_subscribers_id'), 'newsletter_subscribers', ['id'], unique=False)
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('page_views', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_page_views_created_at'), table_name='page_views')
    op.drop_index(op.f('idx_page_views_page'), table_name='page_views')
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.alter_column('popular_calculators', 'last_calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_popular_calculators_rank'), table_name='popular_calculators', postgresql_where='(rank_30d IS NOT NULL)')
    op.create_index(op.f('ix_popular_calculators_id'), 'popular_calculators', ['id'], unique=False)
    op.add_column('redirects', sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True))
    op.alter_column('redirects', 'last_hit_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_redirects_id'), 'redirects', ['id'], unique=False)
    op.create_foreign_key(None, 'redirects', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('related_calculators', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_related_calculators_id'), 'related_calculators', ['id'], unique=False)
    op.drop_index(op.f('idx_reviewers_slug'), table_name='reviewers')
    op.drop_constraint(op.f('reviewers_slug_key'), 'reviewers', type_='unique')
    op.create_index(op.f('ix_reviewers_id'), 'reviewers', ['id'], unique=False)
    op.create_index(op.f('ix_reviewers_slug'), 'reviewers', ['slug'], unique=True)
    op.add_column('role_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_saved_calculations_id'), 'saved_calculations', ['id'], unique=False)
    op.alter_column('search_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_search_history_query'), table_name='search_history')
    op.create_index(op.f('ix_seo_metadata_id'), 'seo_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    op.alter_column('sitemaps', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_sitemaps_id'), 'sitemaps', ['id'], unique=False)
    op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.add_column('user_roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_column('user_roles', 'updated_at')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    op.drop_index(op.f('ix_sitemaps_id'), table_name='sitemaps')
    op.alter_column('sitemaps', 'generated_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_index(op.f('ix_seo_metadata_id'), table_name='seo_metadata')
    op.create_index(op.f('idx_search_history_query'), 'search_history', ['normalized_query', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('search_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_saved_calculations_id'), table_name='saved_calculations')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'updated_at')
    op.drop_index(op.f('ix_reviewers_slug'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_id'), table_name='reviewers')
    op.create_unique_constraint(op.f('reviewers_slug_key'), 'reviewers', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_reviewers_slug'), 'reviewers', ['slug'], unique=False)
    op.drop_index(op.f('ix_related_calculators_id'), table_name='related_calculators')
    op.drop_column('related_calculators', 'updated_at')
    op.drop_constraint(None, 'redirects', type_='foreignkey')
    op.drop_index(op.f('ix_redirects_id'), table_name='redirects')
    op.alter_column('redirects', 'last_hit_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('redirects', 'updated_by')
    op.drop_index(op.f('ix_popular_calculators_id'), table_name='popular_calculators')
    op.create_index(op.f('idx_popular_calculators_rank'), 'popular_calculators', ['rank_30d'], unique=False, postgresql_where='(rank_30d IS NOT NULL)')
    op.alter_column('popular_calculators', 'last_calculated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.create_index(op.f('idx_page_views_page'), 'page_views', ['page_type', 'page_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_page_views_created_at'), 'page_views', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('page_views', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'read_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.drop_index(op.f('ix_newsletter_subscribers_id'), table_name='newsletter_subscribers')
    op.alter_column('newsletter_subscribers', 'unsubscribed_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('newsletter_subscribers', 'subscribed_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('newsletter_subscribers', 'verified_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_navigation_items_id'), table_name='navigation_items')
    op.create_index(op.f('idx_navigation_items_parent'), 'navigation_items', ['parent_id', 'sort_order'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_media_folders_id'), table_name='media_folders')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_homepage_sections_id'), table_name='homepage_sections')
    op.drop_index(op.f('ix_guides_slug'), table_name='guides')
    op.drop_index(op.f('ix_guides_id'), table_name='guides')
    op.create_index(op.f('idx_guides_slug'), 'guides', ['slug'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint(op.f('guides_slug_key'), 'guides', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('guides', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('guides', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_guide_sections_id'), table_name='guide_sections')
    op.create_index(op.f('idx_guide_sections_guide_id'), 'guide_sections', ['guide_id'], unique=False)
    op.drop_index(op.f('ix_guide_media_id'), table_name='guide_media')
    op.drop_column('guide_media', 'updated_at')
    op.drop_index(op.f('ix_guide_calculators_id'), table_name='guide_calculators')
    op.drop_column('guide_calculators', 'updated_at')
    op.drop_index(op.f('ix_footer_links_id'), table_name='footer_links')
    op.drop_index(op.f('ix_footer_columns_id'), table_name='footer_columns')
    op.drop_index(op.f('ix_custom_pages_slug'), table_name='custom_pages')
    op.drop_index(op.f('ix_custom_pages_id'), table_name='custom_pages')
    op.create_index(op.f('idx_custom_pages_slug'), 'custom_pages', ['slug'], unique=False)
    op.create_unique_constraint(op.f('custom_pages_slug_key'), 'custom_pages', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_index(op.f('idx_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_calculators_slug'), table_name='calculators')
    op.drop_index(op.f('ix_calculators_id'), table_name='calculators')
    op.create_index(op.f('idx_calculators_slug'), 'calculators', ['slug'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_calculators_is_featured'), 'calculators', ['is_featured'], unique=False, postgresql_where='((is_featured = true) AND (is_published = true))')
    op.create_index(op.f('idx_calculators_category_id'), 'calculators', ['category_id'], unique=False)
    op.create_index(op.f('idx_calculators_author_id'), 'calculators', ['author_id'], unique=False)
    op.create_unique_constraint(op.f('calculators_slug_key'), 'calculators', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('calculators', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('calculators', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_calculator_sections_id'), table_name='calculator_sections')
    op.drop_index(op.f('ix_calculator_references_id'), table_name='calculator_references')
    op.drop_column('calculator_references', 'updated_at')
    op.drop_index(op.f('ix_calculator_outputs_id'), table_name='calculator_outputs')
    op.create_index(op.f('idx_calculator_outputs_calculator_id'), 'calculator_outputs', ['calculator_id'], unique=False)
    op.drop_index(op.f('ix_calculator_media_id'), table_name='calculator_media')
    op.drop_column('calculator_media', 'updated_at')
    op.drop_index(op.f('ix_calculator_inputs_id'), table_name='calculator_inputs')
    op.create_index(op.f('idx_calculator_inputs_calculator_id'), 'calculator_inputs', ['calculator_id'], unique=False)
    op.drop_index(op.f('ix_calculator_formulas_id'), table_name='calculator_formulas')
    op.drop_index(op.f('ix_calculator_faqs_id'), table_name='calculator_faqs')
    op.create_index(op.f('idx_calculator_faqs_calculator_id'), 'calculator_faqs', ['calculator_id'], unique=False)
    op.drop_index(op.f('ix_calculator_examples_id'), table_name='calculator_examples')
    op.drop_index(op.f('ix_calculator_charts_id'), table_name='calculator_charts')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_column('bookmarks', 'updated_at')
    op.drop_index(op.f('ix_blog_sections_id'), table_name='blog_sections')
    op.create_index(op.f('idx_blog_sections_blog_post_id'), 'blog_sections', ['blog_post_id'], unique=False)
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.create_index(op.f('idx_blog_posts_slug'), 'blog_posts', ['slug'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_blog_posts_category_id'), 'blog_posts', ['category_id'], unique=False)
    op.create_index(op.f('idx_blog_posts_author_id'), 'blog_posts', ['author_id'], unique=False)
    op.create_unique_constraint(op.f('blog_posts_slug_key'), 'blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('blog_posts', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('blog_posts', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_blog_media_id'), table_name='blog_media')
    op.drop_column('blog_media', 'updated_at')
    op.drop_index(op.f('ix_blog_calculators_id'), table_name='blog_calculators')
    op.drop_column('blog_calculators', 'updated_at')
    op.drop_index(op.f('ix_authors_slug'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.create_index(op.f('idx_authors_slug'), 'authors', ['slug'], unique=False)
    op.create_unique_constraint(op.f('authors_slug_key'), 'authors', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_audit_logs_user'), 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_resource'), 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_explanations_id'), table_name='ai_explanations')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_index(op.f('ix_advertisements_id'), table_name='advertisements')
    op.alter_column('advertisements', 'end_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('advertisements', 'start_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('advertisements', 'updated_by')
    # ### end Alembic commands ###
